apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/watcharakrit-th/gitops-repo.git
    targetRevision: main
    path: dev
    # directory:
    #   recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
