apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jenkins-sonar
  namespace: jenkins
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: jenkins/sonar
  destination:
    name: jenkins-sonar
    create: true
  refreshAfter: 1h
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: jenkins/admin
  destination:
    name: jenkins-admin
    create: true
  refreshAfter: 1h
