apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-config
  namespace: vault-demo
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: vault-demo/config
  destination:
    name: app-config
    create: true
  refreshAfter: 30s
