apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jenkins-dockerhub
  namespace: jenkins-builds
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: jenkins/dockerhub
  destination:
    name: jenkins-dockerhub
    create: true
  refreshAfter: 1h
