apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: jenkins
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
        memory: "128Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "1"
        memory: "2Gi"
      min:
        cpu: "10m"
        memory: "16Mi"
