apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-db
  namespace: postgres
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: postgres/sonar
  destination:
    name: postgres-db
    create: true
  refreshAfter: 1h
